### ISSUE TITLE
Where do I add my ocr space api key?

### ISSUE THREAD

**Issue by ghost** [setsumi/OCRGet#2]
Where do I add my ocr space apikey? or does it use web demo?

**Comment by setsumi** [comment]
`OCRGet.ini` file (created after first run), it should be clear how to with the example in there. Use the proper code editor such as Notepad++ to edit this file.
Free API is used by default. I'm not well versed with API keys, but here's another URL just in case `http://apipro2.ocr.space/parse/image`

**Comment by setsumi** [comment]
Regarding limits I don't know, it was from the official API C# [demo project](https://github.com/A9T9/Free-OCR-API-CSharp)
