### ISSUE TITLE
Feature req: Improve OCR Space parsing linebreak

### ISSUE THREAD

**Issue by ghost** [setsumi/OCRGet#4]
I will send the examples you will understand me. I will put comparison link
comparison link https://slow.pics/c/F9toPdb7

from a general point of view ocr space is definitely much better, but when ocring picture based subtitles with ocr space it erases the gaps etc. when I use the same in linux with a basic bash script (sends to api with curl) I had no problem, I wonder if there is something wrong with the implementation? I don't have the subtitle I had that problem with and I don't remember which one it was, but when I tried it with both windows (OCR GET) and linux (curl) on the same file, I saw that it deleted extra gaps in ocr.get with these settings.

I guess it forgots to add extra space when it deletes line breaks on ocr.space api.
```
I \n
Love \n
you.
```
should be
```
I Love You
```
not ``` ILoveYou ```

**Comment by setsumi** [comment]
I see, for languages with spaces, line breaks should be treated as space separators and not just removed making words stick together. Will look into it.

**Comment by setsumi** [comment]
Well, program is updated, but the issue on the picture above seems unrelated. It appears the used Engine 2 is the culprit returning text like this regardless of OCRGet line break options. Switching to Engine 1 made line breaks to appear. If you intend to use specifically Engine 2 then may be try to ask on [their forum](https://forum.ui.vision/c/ocr-api/10)? I'm not good with asking people, sorry.

**Comment by setsumi** [comment]
To add keys etc, close the program end edit `OCRGet.ini` file directly.
After that run the program and right click on each engine to select its credential. Current credential depends on currently selected engine (Engine 1 or Engine 2) and displayed in status bar below with additional mouse hover tool tip.
